services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: wa-bot-api-dev
    network_mode: host
    volumes:
      - .:/app
      - /home/aorus/bimalord-bot/database:/app/database
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
      - LIGHTPANDA_CDP_URL=http://localhost:9222
    depends_on:
      - lightpanda
    stdin_open: true
    tty: true
    command: tail -f /dev/null

  lightpanda:
    image: lightpanda/browser:nightly
    container_name: wa-bot-lightpanda
    network_mode: host
    restart: always

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    container_name: wa-bot-fe-dev
    network_mode: host
    volumes:
      - ./web:/app
    stdin_open: true
    tty: true
    command: tail -f /dev/null
