FROM golang:1.24-alpine

WORKDIR /app

# Instal dependensi sistem yang dibutuhkan untuk build (CGO) dan tool eksternal
RUN apk add --no-cache \
    gcc \
    musl-dev \
    sqlite-dev \
    ffmpeg \
    libwebp-tools \
    python3 \
    py3-pip \
    bash \
    curl \
    git

# Instal air untuk hot-reload (opsional)
RUN go install github.com/air-verse/air@latest

# Command agar container tetap menyala
CMD ["tail", "-f", "/dev/null"]
