services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wa-bot-api
    restart: always
    volumes:
      - ./database:/app/database
    ports:
      - "3090:3090"
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
      - LIGHTPANDA_CDP_URL=http://lightpanda:9222
    depends_on:
      - lightpanda

  lightpanda:
    image: lightpanda/browser:nightly
    container_name: wa-bot-lightpanda
    restart: always
