FROM golang:1.25-alpine

WORKDIR /app

# Install base dependencies
RUN apk add --no-cache \
    gcc \
    musl-dev \
    sqlite-dev \
    ffmpeg \
    libwebp-tools \
    python3 \
    py3-pip \
    bash \
    curl \
    git

# Install air for hot-reload
RUN go install github.com/air-verse/air@v1.61.7

# Command to keep container running
CMD ["tail", "-f", "/dev/null"]
